return {
  ["EdenEast/nightfox.nvim"] = require "user.plugins.nightfox",
  ["akinsho/git-conflict.nvim"] = require "user.plugins.git-conflict",
  ["andymass/vim-matchup"] = require "user.plugins.vim-matchup",
  ["danymat/neogen"] = require "user.plugins.neogen",
  ["dhruvasagar/vim-table-mode"] = require "user.plugins.vim-table-mode",
  ["echasnovski/mini.nvim"] = require "user.plugins.mini",
  ["ethanholz/nvim-lastplace"] = require "user.plugins.nvim-lastplace",
  ["famiu/bufdelete.nvim"] = { disable = true },
  ["folke/zen-mode.nvim"] = require "user.plugins.zen-mode",
  ["hrsh7th/cmp-calc"] = require "user.plugins.cmp-calc",
  ["hrsh7th/cmp-emoji"] = require "user.plugins.cmp-emoji",
  ["hrsh7th/cmp-omni"] = require "user.plugins.cmp-omni",
  ["mehalter/mason-nvim-dap.nvim"] = require "user.plugins.mason-nvim-dap",
  ["jc-doyle/cmp-pandoc-references"] = require "user.plugins.cmp-pandoc-references",
  ["jose-elias-alvarez/typescript.nvim"] = require "user.plugins.typescript",
  ["lukas-reineke/headlines.nvim"] = require "user.plugins.headlines",
  ["lukas-reineke/indent-blankline.nvim"] = { disable = true },
  ["max397574/better-escape.nvim"] = { disable = true },
  ["mfussenegger/nvim-dap"] = require "user.plugins.dap",
  ["mtikekar/nvim-send-to-term"] = require "user.plugins.nvim-send-to-term",
  ["mxsdev/nvim-dap-vscode-js"] = require "user.plugins.nvim-dap-vscode-js",
  ["nanotee/sqls.nvim"] = require "user.plugins.sqls",
  ["nvim-telescope/telescope-file-browser.nvim"] = require "user.plugins.telescope-file-browser",
  ["nvim-telescope/telescope-hop.nvim"] = require "user.plugins.telescope-hop",
  ["nvim-telescope/telescope-media-files.nvim"] = require "user.plugins.telescope-media-files",
  ["nvim-telescope/telescope-project.nvim"] = require "user.plugins.telescope-project",
  ["nvim-treesitter/nvim-treesitter-textobjects"] = require "user.plugins.nvim-treesitter-textobjects",
  ["p00f/clangd_extensions.nvim"] = require "user.plugins.clangd_extensions",
  ["phaazon/hop.nvim"] = require "user.plugins.hop",
  ["rcarriga/nvim-dap-ui"] = require "user.plugins.dapui",
  ["theHamsta/nvim-dap-virtual-text"] = require "user.plugins.nvim-dap-virtual-text",
  ["wakatime/vim-wakatime"] = require "user.plugins.vim-wakatime",
  ["ziontee113/syntax-tree-surfer"] = require "user.plugins.syntax-tree-surfer",
  ["nvim-neo-tree/neo-tree.nvim"] = require "user.plugins.neo-tree",
  ["voldikss/vim-browser-search"] = require "user.plugins.vim-browser-search",
  ["normen/vim-pio"] = require "user.plugins.vim-pio",
  ["iamcco/markdown-preview.nvim"] = require "user.plugins.markdown-preview",
  ["Pocco81/auto-save.nvim"] = require "user.plugins.auto-save",
  ["folke/trouble.nvim"] = require "user.plugins.trouble",
}
